apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-flask-app
  template:
    metadata:
      labels:
        app: simple-flask-app
    spec:
      containers:
      - name: simple-flask-app
        image: koil123-gfhufkgvf0dmaqam.azurecr.io1/simple-flask-app:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: simple-flask-service
spec:
  type: LoadBalancer
  selector:
    app: simple-flask-app
  ports:
  - port: 80
    targetPort: 5000
